V1.28.0
ConsumerDataStandardsAustralia/DefinitelyTyped pull request #21
Opened 2023-12-15 04:58 UTC by abeheron1

Added new definitions for as per published v1.28.0

- energy API
- banking API

Fixed issue: https://trello.com/c/8DZW8DBl

2023-12-19 22:22 UTC, vadkor requested changes
Almost perfect. Just a cosmetic touch-up needed.

2023-12-19 22:22 UTC, vadkor commented on types/consumer-data-standards/banking/index.d.ts
> +    [k: string]: unknown;
Please move to be the last member of the interface.

2023-12-19 22:22 UTC, vadkor commented on types/consumer-data-standards/banking/index.d.ts
> +        isQueryParamUnsupported?: boolean | null;
Please move so that `[k: string]: unknown;` is the last member of the interface.

2024-01-02 05:13 UTC, tom-schier approved these changes

2024-02-28 22:48 UTC, vadkor approved these changes

2024-02-28 23:18 UTC, merged